name: test wrapper

permissions:
  contents: read
  id-token: write

# Set concurrency to 1 to rewrite firebase remote config
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
  merge_group:
jobs:
  call-test:
    uses: ./.github/workflows/test.yaml
  status-check:
    runs-on: ubuntu-latest
    needs: [call-test]
    if: always()
    steps:
      - run: |
          if [[ "${{ needs.call-test.result }}" == 'success' ]]; then
            exit 0
          elif [[ "${{ needs.call-test.result }}" == 'skipped' || "${{ needs.call-test.result }}" == 'cancelled' ]]; then
            exit 0
          fi
